# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 'Alibaba Easy Excel - 简单、省内存的Java解析Excel工具'
description: '简单、省内存的Java解析Excel工具'
keywords: 'Excel,Easy Excel,easyexcel 官方,easyexcel,Java,xls,xlsx,省内存,简单,解析Excel,poi,oom,OutOfMemoryError'
author: 'jipengfei'
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://alibaba-easyexcel.github.io
# root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../themes/hexo-theme-doc

theme_config:
  favicon: images/favicon.ico

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'
